const fs = require('fs');
const path = require('path');
const vm = require('vm');

function loadReportNarrativeApi() {
  const source = fs.readFileSync(path.join(__dirname, '..', 'app.js'), 'utf8');
  const start = source.indexOf('function _surveyHasTypeAorBFindings');
  const end = source.indexOf('// ── Propulsion narrative builder');
  if (start < 0 || end < 0 || end <= start) throw new Error('Description helper block was not found in app.js');

  const context = {
    document: { getElementById: () => null },
    window: {},
    parseYearMakeModel(value) {
      const match = String(value || '').trim().match(/^(\d{4})\s+(\S+)(?:\s+(.+))?$/);
      return match ? { year: match[1], make: match[2], model: match[3] || '' } : { year: '', make: '', model: '' };
    },
    findBoatSpecs: () => null,
    lookupEngineType: (make) => (/kubota/i.test(make || '') ? 'inboard' : ''),
    _surveyHasSecondEngine: () => false
  };
  vm.runInNewContext(
    source.slice(start, end) +
      '\nthis.api = { buildDescriptionFromSurvey, _descriptionForReport, _buildFindingOverviewSummary };',
    context
  );
  return context.api;
}

function ciaoBabySurvey() {
  return {
    id: '1777042617097',
    vesselName: 'Ciao Baby II',
    yearMakeModel: '2004 Catalina 350',
    vesselType: 'sail',
    boatStyle: 'Sloop',
    construction: 'Fibreglass',
    hullType: 'Displacement',
    loa: `35'4"`,
    beam: `12'4"`,
    maxDraft: `4'10"`,
    displacement: '14,250 lbs',
    ballast: '5,500 lbs',
    keelType: 'Wing',
    totalSailArea: '601 sq ft',
    hullColour: 'White',
    bootStripeColour: 'Dark Blue',
    deckColour: 'White',
    engineMake: 'Kubota',
    engineModel: 'V1305-ES',
    engineHP: '27.2 kW',
    fuelType: 'Diesel',
    driveType: 'shaft',
    electricalSystem: '12V DC / 120V AC (30 amp shore power)',
    overallCondition: 'Average',
    items: {
      'Main mast': { mastStepping: 'Deck stepped', mastTrackType: 'In-mast roller furling' },
      'Hot water tank, plumbing and electrical': { rating: 'A - Critical' },
      'Shore power inlet': { rating: 'B - Needs Attention' }
    }
  };
}

describe('Version 2-style vessel description', () => {
  const api = loadReportNarrativeApi();

  it('builds the Ciao Baby II narrative once, without redundant sections', () => {
    const description = api.buildDescriptionFromSurvey(ciaoBabySurvey());
    assert.equal(description, [
      `Ciao Baby II was a 2004 Catalina 350, a fibreglass, sloop-rigged displacement monohull. The vessel had an overall length of 35'4", a beam of 12'4", a wing keel with a maximum draft of 4'10", and a displacement of 14,250 lb, with reported ballast of 5,500 lb. Ciao Baby II was fitted with a deck-stepped aluminium mast and in-mast roller furling. Total sail area was reported as 601 sq. ft. The hull was finished in white with a dark blue boot stripe, and the deck was white.`,
      `Auxiliary power was provided by a Kubota V1305-ES diesel inboard engine. The engine data plate indicated an output of 27.2 kW. However, the marine propulsion rating was not independently verified. The engine drove a propeller through a shaft drive. The gearbox had been removed for service and the exhaust system was disconnected. Engine, gearbox, exhaust, and drivetrain operation were not verified.`,
      `Below decks, the vessel featured one cabin and one head. The electrical system was configured for 12V DC and 120V AC service, with 30-amp shore power. Recorded navigation and communication fit-out included VHF radio, magnetic compass, wind instruments, autopilot, and depth sounder. Testing status and limitations for each item are stated in the Detailed Survey Findings.`,
      `The vessel was rated in average overall condition after consideration of its age, equipment, observed condition, and the findings noted in this report, subject to correction of the Type A and Type B findings. Refer to the Findings and Recommendations section for details.`
    ].join('\n\n'));
    assert.equal((description.match(/Below decks/g) || []).length, 1);
    assert.equal((description.match(/gearbox had been removed/g) || []).length, 1);
    assert.equal((description.match(/average overall condition/g) || []).length, 1);
  });

  it('rebuilds auto-generated report text but preserves manual copy verbatim', () => {
    const autoSurvey = { ...ciaoBabySurvey(), vesselDescription: 'stale repeated copy', descriptionAutoGenerated: true };
    assert.equal(api._descriptionForReport(autoSurvey), api.buildDescriptionFromSurvey(autoSurvey));

    const manual = { ...ciaoBabySurvey(), vesselDescription: 'My manually edited vessel description.', descriptionAutoGenerated: false };
    assert.equal(api._descriptionForReport(manual), 'My manually edited vessel description.');
  });
});

describe('Findings Overview A/B item summaries', () => {
  const api = loadReportNarrativeApi();

  it('returns finding count plus brief coded item names', () => {
    assert.deepEqual(
      api._buildFindingOverviewSummary([
        { code: 'B-1', label: 'Shore power inlet' },
        { code: 'B-2', label: 'Propane locker' },
        { code: 'B-3', label: 'Engine seacock' }
      ]),
      {
        countText: '3 findings',
        items: ['B-1 Shore power inlet', 'B-2 Propane locker', 'B-3 Engine seacock']
      }
    );
  });
});
